### ISSUE TITLE
rewrite of vcl_hash

### ISSUE THREAD

**Issue by pasztorl** [pczerkas/kube-apps-httpcache#14]
Hi,

First, this code works great big thanks for that!
My problem probably not a bug, but a question.
So the backend service changes the content by the user agent defining the client is a desktop or a mobile.
I've found this vcl: https://github.com/varnishcache/varnish-devicedetect and I added this to the vcl template.
Now I see the extra added headers.
```
-   VCL_call       RECV
...
-   ReqHeader      X-UA-Device: desktop
-   VCL_use        l004_20240416_135654_82836 via l001
-   VCL_return     vcl
```

After doing this I defined a vcl_hash like this:
```
        sub vcl_hash {
            hash_data(req.url);
            hash_data(req.http.X-UA-Device);
            if (req.http.host) {
                hash_data(req.http.host);
                
            } else {
                hash_data(server.ip);
            }
            return (lookup);
        }
```

It not worked, so I checked the varnishlog:
```
-   VCL_call       RECV
-   VCL_return     hash
-   ReqUnset       accept-encoding: identity
-   VCL_call       HASH
-   Hash           "/article/1/1712303819_43457_abstract_dual_screen_dual_monitor_abstract_lights_dual_screen.jpg%00"
-   Hash           "example.net%00"
-   VCL_return     lookup
```

So it seems the custom vcl_hash not executed, the default vcl_hash used. There is a trick which I missed to modify the built-in one?

**Comment by pasztorl** [comment]
Oh sorry, I need to add this to the response header.

**Comment by pasztorl** [comment]
It looks like if the values.vclTemplate sets the header the cache.applications[*].vclTemplate not see it. Am I miss something?

**Comment by pczerkas** [comment]
@pasztorl sorry about that, but somehow I did not get email notification about this issue. I'l try to look at this ...
